"""empty message

Revision ID: 348e0b1c22c6
Revises: None
Create Date: 2015-07-19 17:45:16.593069

"""

# revision identifiers, used by Alembic.
revision = '348e0b1c22c6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(convert_unicode=True), nullable=True),
    sa.Column('first_listed', sa.DateTime(), nullable=True),
    sa.Column('last_listed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock_key_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('earnings', sa.Numeric(), nullable=True),
    sa.Column('roe', sa.Numeric(), nullable=True),
    sa.Column('book_value', sa.Numeric(), nullable=True),
    sa.Column('pe', sa.Numeric(), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('total_debt_ratio', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['stock'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_key_stats')
    op.drop_table('stock')
    ### end Alembic commands ###
